name: Publish
run-name: ${{ gitea.actor }} is publishing your site using Gitea Actions 🚀

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: sagittarius.premium.hostns.io
          username: adcmnetworks
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          uploads: |
            ./export => /home/adcmnetworks/csbox
          delete: 'true'
          ignore: |
            *.git
            */**/*git*