name: Publish to Server
run-name: ${{ gitea.actor }} is publishing your site using Gitea Actions 🚀

on:
  workflow_dispatch:
  # Trigger the workflow on push
  push:
    branches: [main]

# Authenticate to the the server via ssh
# and run our deployment script (sftp upload)
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ vars.GIT_FOLDER }}
          target: ${{ vars.SSH_FOLDER }}